theme: jekyll-theme-architect
title: Boicote à Empresas de Esquerda
description: Boicote a todas empresas, usam das mídias para fazer politicagem, às que defendem ideologias macabras e as que estão lucrando em cima da desgraça do povo.